apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wa-task-management-api
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/wa/task-management-api:prod-11d8a9f-20230110125124 #{"$imagepolicy": "flux-system:wa-task-management-api"}
      environment:
        REFRESH_FLAG: ""
