apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dtsse-ardoq-adapter
  namespace: flux-system
spec:
  path: ./apps/dtsse-ardoq-adapter/${ENVIRONMENT}/base
  postBuild:
    substitute:
      NAMESPACE: "dtsse-ardoq-adapter"
      TEAM_NOTIFICATION_CHANNEL: "rse"
