apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: repl-docmosis-service
  namespace: ethos
spec:
  releaseName: repl-docmosis-service
  values:
    java:
      ingressClass: traefik-private
      disableIngressClassAnnotation: true
      image: hmctspublic.azurecr.io/ethos/repl-docmosis-backend:prod-dfde219-20221214164732 #{"$imagepolicy": "flux-system:repl-docmosis-service"}
      environment:
        SECURE_DOC_STORE_FEATURE: false
