# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    curl $(WEBHOOK_URL) -H 'Content-Type: application/json' -d '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.adaptive","contentUrl":null,"content":{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.5","body":[{"type":"TextBlock","text":"Azure Devops Pipeline Succeded","size":"Large","weight":"Bolder","wrap":true,"color":"Good"},{"type":"ColumnSet","columns":[{"type":"Column","width":"stretch","verticalContentAlignment":"Top","items":[{"type":"Image","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/1200px-Eo_circle_green_checkmark.svg.png","size":"Small","horizontalAlignment":"Center"}]},{"type":"Column","width":"stretch","verticalContentAlignment":"Center"},{"type":"Column","width":"stretch","items":[{"type":"Image"}]},{"type":"Column","width":"stretch"},{"type":"Column","width":"stretch"},{"type":"Column","width":"stretch"}]},{"type":"ColumnSet","columns":[{"type":"Column","width":"stretch","items":[{"type":"TextBlock","text":"Branch","wrap":true,"weight":"Bolder"},{"type":"TextBlock","text":"Status","wrap":true,"weight":"Bolder"},{"type":"TextBlock","text":"Triggered By","wrap":true,"weight":"Bolder"}]},{"type":"Column","width":"stretch","items":[{"type":"TextBlock","text":"dev_core","wrap":true,"weight":"Lighter","isSubtle":true},{"type":"TextBlock","text":"Succeded","wrap":true,"weight":"Lighter","isSubtle":true,"color":"Attention"},{"type":"TextBlock","text":"Praveen Adusumilli","wrap":true,"isSubtle":false,"color":"Default","weight":"Default"}]}]},{"type":"TextBlock","text":"This is a notification using webhook connectors","isSubtle":true,"wrap":true}],"actions":[{"type":"Action.OpenUrl","title":"See Build","url":"https://dev.azure.com"}]}}]}'
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
