---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: draft-store-service
  namespace: rpe
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: draft-store-service
  rollback:
    enable: true
    retry: true
  chart:
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    name: draft-store-service
    version: 2.0.13
  values:
    java:
      replicas: 2
      readinessDelay: 45
      readinessTimeout: 5
      readinessPeriod: 15
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/draft-store/service:prod-eb274480
     
