apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bar-web
spec:
  releaseName: bar-web
  values:
    nodejs:
      image: hmctspublic.azurecr.io/bar/web:prod-4ade93e-20230103233234 #{"$imagepolicy": "flux-system:bar-web"}
      environment:
        DUMMY_RESTART_VAR: true
