apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fees-register-frontend
spec:
  releaseName: fees-register-frontend
  values:
    nodejs:
      image: hmctspublic.azurecr.io/fees-register/frontend:prod-1ce7274-20230105213643 #{"$imagepolicy": "flux-system:perftest-fees-register-frontend"}
      environment:
        DUMMY_RESTART_VAR: true
