apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ccd-definition-store-api
spec:
  releaseName: ccd-definition-store-api
  values:
    java:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/ccd/definition-store-api:prod-792f815-20230110101016 #{"$imagepolicy": "flux-system:ccd-definition-store-api"}
  chart:
    spec:
      chart: ./stable/ccd-definition-store-api
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
