apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ts-translation-service-int
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/ts/translation-service:prod-d86862a-20230110100628 #{"$imagepolicy": "flux-system:ts-translation-service"}
      disableIngressClassAnnotation: true
      ingressClass: traefik-private
