apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: et
  namespace: et
spec:
  type: 0

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: et-binding
  namespace: et
spec:
  azureIdentity: et
  selector: et
