apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sscs-hearings-api
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/sscs/hearings-api:prod-ac2b33a-20230103134901 #{"$imagepolicy": "flux-system:sscs-hearings-api"}
      environment:
        TRIBUNALS_HEARINGS_LISTENING_ENABLED: true
        TRIBUNALS_EVENT_QUEUE_RETRY_TIMEOUT: 60
        DUMMY_PROPERTY: true
        HMC_HEARINGS_LISTENING_ENABLED: true
