apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ia-case-api
spec:
  values:
    java:
      ingressClass: traefik-private
      disableIngressClassAnnotation: true
      image: hmctspublic.azurecr.io/ia/case-api:prod-175f39f-20221216175323 #{"$imagepolicy": "flux-system:ia-case-api"}
      environment:
        IA_HOME_OFFICE_INTEGRATION_ENABLED: "true"
