name: Flux sanity checks

# yamllint disable-line
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install kubeconform
        run: |
          set -ex
           # renovate: datasource=github-releases depName=yannh/kubeconform
          KUBECONFORM_VERSION=v0.2.2
          curl -sL https://github.com/yannh/kubeconform/releases/download/$KUBECONFORM_VERSION/kubeconform-linux-amd64.tar.gz | tar xz
          cp kubeconform /usr/local/bin/
          chmod +x /usr/local/bin/kubeconform
      - name: Dry run and kubeconform
        run: kubeconform -v
